# Generated by Django 4.0.3 on 2023-01-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_code_model_new',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('teacher_code_name', models.CharField(max_length=200, verbose_name='сюда название кода - для чего')),
                ('teacher_code_line', models.IntegerField(verbose_name='сюда вставляется код')),
                ('status', models.BooleanField(default=False, verbose_name='активирован?')),
            ],
            options={
                'verbose_name': 'Учительский код для регистрации',
                'verbose_name_plural': 'Учительский код для регистрации',
            },
        ),
    ]
