# Generated by Django 4.0.3 on 2023-01-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_cabinets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teacher_code_model_new',
        ),
    ]
