# Generated by Django 4.0.3 on 2023-01-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_cabinets', '0004_alter_document_docfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
